name: Fetch game files

on:
  workflow_call:
    outputs:
      bepinex_version:
        description: "Version of BepInEx"
        value: "6.0.0-be.697+5362580"
      game_build_id:
        description: "Build ID of the game"
        value: ${{ jobs.fetch-game-files.outputs.game_build_id }}
      game_version:
        description: "Version of the game"
        value: ${{ jobs.fetch-game-files.outputs.game_version }}

jobs:
  fetch-game-files:
    name: Fetch game files
    runs-on: windows-latest
    
    permissions:
      packages: read

    outputs:
      game_build_id: ${{ steps.read_dofus_build_id.outputs.dofus_build_id }}
      game_version: ${{ steps.read_dofus_version.outputs.dofus_version }}

    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
        
      - name: Setup Github NPM registry for @dofus-batteries-included namespace
        run: |
          echo @dofus-batteries-included:registry=https://npm.pkg.github.com > ~/.npmrc
          echo //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }} >> ~/.npmrc

      - name: Install Cytrus v6
        run: npm i @dofus-batteries-included/cytrus-v6 -g

      - name: Read current game version
        id: read_dofus_version
        run: |
          $CytrusGameVersion=$(cytrus-v6 version -g dofus -b)
          echo "dofus_version=$($CytrusGameVersion.Split(`"_`")[1])" >> $Env:GITHUB_OUTPUT

      - name: Cache game files
        id: cache-game-files
        uses: actions/cache@v4
        with:
          path: dofus-beta
          key: dofus-beta-${{ steps.read_dofus_version.outputs.dofus_version }}
          
      - name: Checkout
        if: steps.cache-game-files.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: Dofus-Batteries-Included/workflows
          fetch-depth: 0

      - name: Download BepInEx
        if: steps.cache-game-files.outputs.cache-hit != 'true'
        run: curl https://builds.bepinex.dev/projects/bepinex_be/697/BepInEx-Unity.IL2CPP-win-x64-6.0.0-be.697%2B5362580.zip -o BepInEx.zip

      - name: Download latest game files
        if: steps.cache-game-files.outputs.cache-hit != 'true'
        run: cytrus-v6 download -g dofus -b -s "Dofus.exe,*.dll,Dofus_Data/*,Dofus_Data/il2cpp_data/**/*,Dofus_Data/Plugins/**/*,Dofus_Data/Resources/**/*" -o dofus-beta # Use beta for now

      - name: Extract BepInEx
        if: steps.cache-game-files.outputs.cache-hit != 'true'
        run: 7z x BepInEx.zip -odofus-beta -aoa

      - name: Run game once
        if: steps.cache-game-files.outputs.cache-hit != 'true'
        run: node scripts/bepinex-run-until "dofus-beta/Dofus.exe" "Chainloader startup complete"
        timeout-minutes: 10

      - name: Read game build id
        id: read_dofus_build_id
        run: echo "dofus_build_id=$(node scripts/read-build-guid.js dofus-beta/Dofus_Data/boot.config)" >> $Env:GITHUB_OUTPUT

      - name: Display build information
        run: |
          echo "Build id: ${{ steps.read_dofus_build_id.outputs.dofus_build_id }}"
          echo "Version: ${{ steps.read_dofus_version.outputs.dofus_version }}"

      - name: Upload Interop assemblies
        uses: actions/upload-artifact@v4
        with:
          name: interop-assemblies
          path: dofus-beta/BepInEx/interop/*